name: Compile and upload résumé PDF
on:
  push:
    branches:
      - "main"
    paths:
      - "resume.tex"
      - "index.html"
      - "metalogo.png"
      - ".github/workflows/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "resume.tex"
      - "index.html"
      - "metalogo.png"
      - ".github/workflows/**"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          args: -output-directory=build

      - name: Create build directory if it doesn't exist
        run: mkdir -p build

      - name: Copy web assets to build directory
        run: cp index.html metalogo.png build/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
          clean: true
